**Задание 1**

Создайте матрицу 3 на 3, заполненную числами от 1 до 9

Прибавьте к ней матрицу с единицами на диагонале

Умножьте полученную матрицу на вектор (1, 2, 3)

Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
B = A + np.eye(3)
B

array([[  2.,   2.,   3.],
       [  4.,   6.,   6.],
       [  7.,   8.,  10.]])

In [13]:
vec = np.array([1,2,3])
B @ vec

array([ 15.,  34.,  53.])

In [7]:
np.transpose(B)

array([[  2.,   4.,   7.],
       [  2.,   6.,   8.],
       [  3.,   6.,  10.]])

In [9]:
C = np.linalg.inv(B)
C

array([[ -6.00000000e+00,  -2.00000000e+00,   3.00000000e+00],
       [ -1.00000000e+00,   5.00000000e-01,   2.22044605e-17],
       [  5.00000000e+00,   1.00000000e+00,  -2.00000000e+00]])

In [10]:
# проверка обратной матрицы
B@C

array([[  1.00000000e+00,  -2.22044605e-16,   4.44089210e-16],
       [ -1.77635684e-15,   1.00000000e+00,   8.88178420e-16],
       [ -1.77635684e-15,   4.44089210e-16,   1.00000000e+00]])

**Задание 2**
Найдите собственные значения и собственные вектора матрицы:

In [11]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [12]:
np.linalg.eig(m)

(array([ 1.,  4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [26]:
res = np.linalg.eig(m)
res1 = np.transpose(res[1])
print('число 1:', res[0][0], ', вектор 1:', res1[0]/res1[0][1])
print('число 2:', res[0][1], ', вектор 2:', res1[1]/res1[1][1])

число 1: 1.0 , вектор 1: [-2.  1.]
число 2: 4.0 , вектор 2: [ 1.  1.]


**Задание 3**

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [27]:
M = np.array([[2,5],[1,3]])
np.linalg.det(M)

1.0